version: '3.8'
services:
  dev-db: 
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: go8Nest
    networks:
      - go8NestApp
networks:
  go8NestApp: